@base_url = https://localhost:7015/api/categoria

### Listar Categorias ###
GET {{base_url}}/listar

### Criar Categoria ###
POST {{base_url}}/cadastrar
Content-Type: application/json

{
    "nome": "romopolis"
}

###Patch
PATCH {{base_url}}/alterar/7
Content-Type: application/json

{
    "nome": "arrozdoce"
}
