@base_url = https://localhost:7015/api/tarefa

### Listar Tarefas ###
GET {{base_url}}/listar

### Criar Tarefa ###
POST {{base_url}}/cadastrar
Content-Type: application/json

{
  "Titulo": "Compras no Supermercado",
  "Descricao": "1. Fazer lista de compras: pão, leite, ovos, frutas, vegetais",
  "CategoriaId": 8
}
###Patch
PATCH {{base_url}}/alterar/3
Content-Type: application/json

###GET
GET {{base_url}}/listar/status/
[Route("listar/status/{status : string}}")]

